# Generated by Django 5.1.2 on 2024-11-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('profile', models.FileField(upload_to='teams/,')),
                ('twitter_url', models.CharField(max_length=78)),
                ('instagram_url', models.CharField(max_length=78)),
                ('facebook_url', models.CharField(max_length=78)),
                ('linkedin_url', models.CharField(max_length=78)),
            ],
        ),
    ]
